/**
 * Project-wide semantic icon mapping.
 *
 * Keep all icon components on the package entrypoint. Importing a mix of
 * deep ESM paths and the package entrypoint can make Vite pre-bundle two
 * copies of React, which breaks Ant Design's hook-based icon renderer at
 * runtime after lazy chunks load.
 */
import {
  AimOutlined,
  ApartmentOutlined,
  AppstoreOutlined,
  ArrowRightOutlined,
  ArrowUpOutlined,
  AuditOutlined,
  BankOutlined,
  BarChartOutlined,
  BellOutlined,
  BranchesOutlined,
  BulbOutlined,
  CalculatorOutlined,
  CheckCircleFilled,
  CheckOutlined,
  CloseOutlined,
  CompassOutlined,
  DatabaseOutlined,
  DeleteOutlined,
  DislikeOutlined,
  DownloadOutlined,
  DownOutlined,
  EditOutlined,
  ExportOutlined,
  FileDoneOutlined,
  FileExcelOutlined,
  FileOutlined,
  FileSearchOutlined,
  FileTextOutlined,
  FolderAddOutlined,
  FolderOpenOutlined,
  FolderOutlined,
  FormatPainterOutlined,
  FormOutlined,
  GlobalOutlined,
  HistoryOutlined,
  InboxOutlined,
  InfoCircleOutlined,
  KeyOutlined,
  LeftOutlined,
  LikeOutlined,
  LogoutOutlined,
  MailOutlined,
  MenuFoldOutlined,
  MenuOutlined,
  MenuUnfoldOutlined,
  MergeOutlined,
  MessageOutlined,
  MoreOutlined,
  MinusOutlined,
  OrderedListOutlined,
  PaperClipOutlined,
  PartitionOutlined,
  PlusOutlined,
  QuestionCircleFilled,
  ReloadOutlined,
  RightOutlined,
  RobotOutlined,
  RiseOutlined,
  SafetyCertificateFilled,
  SafetyCertificateOutlined,
  SearchOutlined,
  SendOutlined,
  SettingOutlined,
  StopFilled,
  ThunderboltOutlined,
  UpOutlined,
  UploadOutlined,
  UserOutlined,
  WarningFilled,
} from "@ant-design/icons";

export {
  ArrowRightOutlined as IconArrowRight,
  ExportOutlined as IconExternalLink,
  ArrowUpOutlined as IconArrowUp,
  DownloadOutlined as IconDownload,
  UploadOutlined as IconUpload,
  ReloadOutlined as IconRefresh,
  HistoryOutlined as IconHistory,
  DownOutlined as IconChevronDown,
  LeftOutlined as IconChevronLeft,
  RightOutlined as IconChevronRight,
  UpOutlined as IconChevronUp,
  MenuFoldOutlined as IconSidebarRight,
  MenuFoldOutlined as IconSidebarCollapse,
  MenuUnfoldOutlined as IconSidebarExpand,
  MenuOutlined as IconMenu,
  PlusOutlined as IconPlus,
  CloseOutlined as IconClose,
  MoreOutlined as IconMore,
  MinusOutlined as IconMinimize,
  StopFilled as IconStop,
  SendOutlined as IconSend,
  PaperClipOutlined as IconAttach,
  EditOutlined as IconRename,
  DeleteOutlined as IconDelete,
  InboxOutlined as IconArchive,
  BranchesOutlined as IconBranches,
  MergeOutlined as IconMerge,
  PartitionOutlined as IconOrchestration,
  FileOutlined as IconFile,
  FileTextOutlined as IconFileText,
  FileExcelOutlined as IconFileSpreadsheet,
  FileDoneOutlined as IconFileCheck,
  FileSearchOutlined as IconFileSearch,
  FolderOutlined as IconFolder,
  FolderOpenOutlined as IconFolderOpen,
  FolderAddOutlined as IconFolderPlus,
  AppstoreOutlined as IconFolderManager,
  DatabaseOutlined as IconDatabase,
  BarChartOutlined as IconChart,
  SearchOutlined as IconSearch,
  SettingOutlined as IconSettings,
  GlobalOutlined as IconGlobe,
  InfoCircleOutlined as IconInfo,
  CheckOutlined as IconCheck,
  CheckCircleFilled as IconCheckCircle,
  QuestionCircleFilled as IconHelpCircle,
  AuditOutlined as IconFactCheck,
  SafetyCertificateOutlined as IconChallenge,
  RobotOutlined as IconAuto,
  CalculatorOutlined as IconCalculator,
  RiseOutlined as IconTrendUp,
  OrderedListOutlined as IconChecklist,
  AimOutlined as IconTarget,
  ApartmentOutlined as IconTree,
  ThunderboltOutlined as IconBolt,
  FormatPainterOutlined as IconWand,
  BulbOutlined as IconLightbulb,
  MessageOutlined as IconMessage,
  FormOutlined as IconNewConversation,
  WarningFilled as IconShieldAlert,
  SafetyCertificateFilled as IconShieldCheck,
  StopFilled as IconAbort,
  UserOutlined as IconUser,
  BankOutlined as IconBuilding,
  CompassOutlined as IconCompass,
  LikeOutlined as IconThumbUp,
  DislikeOutlined as IconThumbDown,
  MailOutlined as IconMail,
  BellOutlined as IconBell,
  KeyOutlined as IconKey,
  LogoutOutlined as IconSignOut,
};
